version: '3.8'

services:
  web:
    build: ./moodrss
    container_name: moodrss_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/moodrss/web/staticfiles
    ports:
      - 8000
    security_opt:
      - no-new-privileges:true
    restart: always

  nginx:
    build: ./nginx
    container_name: moodrss_nginx
    volumes:
      - static_volume:/home/moodrss/web/staticfiles
    ports:
      - 1009:80
    depends_on:
      - web
    security_opt:
      - no-new-privileges:true
    restart: always

volumes:
  static_volume:
